version: '3'
services:

    web:
        image: 'dontdrinkandroot/php:20-04-7-4-dev'
        ports:
            - "8000:80"
        depends_on:
            - neo4j
        volumes:
            - ../../:/var/www/
            - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf

    neo4j:
        image: neo4j:4.2
        ports:
            - "7474:7474"
            - "7687:7687"
